version: '3.9'
services:
  postgres:
    container_name: spring-postgres
    image: postgres:15.1-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 108
    volumes:
      - pgdata:/var/lib/postgres/data


volumes:
  pgdata: